# Lab 4

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1mkK0RUgS_ubj8pMRYW93ScdpgldZtckm)

## Exercise 1: Variable Assignment and Basic Operations

Create variables to store the following geospatial data:

- The latitude and longitude of New York City: 40.7128, -74.0060.
- The population of New York City: 8,336,817.
- The area of New York City in square kilometers: 783.8.

Perform the following tasks:

1. Calculate and print the population density of New York City (population per square kilometer).
2. Print the coordinates in the format "Latitude: [latitude], Longitude: [longitude]".

In [1]:
nyc = {
    "latitude": 40.7128,
    "longitude": -74.0060,
    "population": 8336817,
    "area": 783.8
}

# Part 1
print(nyc["population"] / nyc["area"])

# Part 2
print(f"Latitude: {nyc['latitude']}, Longitude: {nyc['longitude']}")

10636.408522582293
Latitude: 40.7128, Longitude: -74.006


## Exercise 2: Working with Strings

Create a string variable to store the name of a city, such as "San Francisco". Perform the following operations:

1. Convert the string to lowercase and print the result.
2. Convert the string to uppercase and print the result.
3. Replace "San" with "Los" in the city name and print the new string.

In [2]:
san = "San Francisco"

# Part 1
print(san.lower())

# Part 2
print(san.upper())

# Part 3
print(san.replace("San", "Los"))

san francisco
SAN FRANCISCO
Los Francisco


## Exercise 3: Using Lists

Create a list of tuples, where each tuple contains the name of a city and its corresponding latitude and longitude:

- New York City: (40.7128, -74.0060)
- Los Angeles: (34.0522, -118.2437)
- Chicago: (41.8781, -87.6298)

Perform the following tasks:

1. Add a new city (e.g., Miami: (25.7617, -80.1918)) to the list.
2. Print the entire list of cities.
3. Slice the list to print only the first two cities.

In [3]:
cities = [
    ("New York City", 40.7128, -74.0060),
    ("Los Angeles", 34.0522, -118.2437),
    ("Chicago", 41.8781, -87.6298)
]

# Part 1
cities.append(("Miami", 25.7617, -80.1918))

# Part 2
print(cities)

# Part 3
print(cities[:2])

[('New York City', 40.7128, -74.006), ('Los Angeles', 34.0522, -118.2437), ('Chicago', 41.8781, -87.6298), ('Miami', 25.7617, -80.1918)]
[('New York City', 40.7128, -74.006), ('Los Angeles', 34.0522, -118.2437)]


## Exercise 4: Using Tuples

Create a tuple to store the coordinates (latitude, longitude) of the Eiffel Tower: (48.8584, 2.2945). Perform the following tasks:

1. Access and print the latitude and longitude values from the tuple.
2. Try to change the latitude value to 48.8585. What happens? Explain why.

In [4]:
tower = (48.8584, 2.2945)

# Part 1
print(tower[0])
print(tower[1])

# Part 2
# tower[0] = 48.8585 # Cannot change tuple value

48.8584
2.2945


## Exercise 5: Working with Sets

Create a set of countries you have visited, such as {"USA", "France", "Germany"}. Perform the following tasks:

1. Add a new country to the set.
2. Try to add the same country again. What happens?
3. Print the updated set.

In [6]:
countries = set(["USA", "France", "Germany"])

# Part 1
countries.add("Canada")

# Part 2
countries.add("Canada") # Will not add duplicates

# Part 3
print(countries)

{'USA', 'Germany', 'France', 'Canada'}


## Exercise 6: Working with Dictionaries

Create a dictionary to store information about a specific geospatial feature, such as a river:

- Name: "Amazon River"
- Length: 6400 km
- Countries: ["Brazil", "Peru", "Colombia"]

Perform the following tasks:

1. Add a new key-value pair to the dictionary to store the river's average discharge (e.g., 209,000 m³/s).
2. Update the length of the river to 6992 km.
3. Print the dictionary.

In [7]:
amzn = {
    "name": "Amazon River",
    "length": 6400,
    "countries": ["Brazil", "Peru", "Colombia"]
}

# Part 1
amzn["discharge"] = 209000

# Part 2
amzn["length"] = 6992

# Part 3
print(amzn)

{'name': 'Amazon River', 'length': 6992, 'countries': ['Brazil', 'Peru', 'Colombia'], 'discharge': 209000}


## Exercise 7: Nested Data Structures

Create a dictionary to represent a city that contains the city's name, population, and coordinates (latitude, longitude):

- Name: "Tokyo"
- Population: 13,515,271
- Coordinates: (35.6895, 139.6917)

Perform the following tasks:

1. Access and print the population of the city.
2. Access and print the city's latitude.
3. Update the population to 14,000,000 and print the updated dictionary.

In [10]:
city = {
    "Name": "Tokyo",
    "Population": 13515271,
    "Coordinates": (35.6895, 139.6917)
}

# Part 1
print(city["Population"])

# Part 2
print(city["Coordinates"][0])

# Part 3
city["Population"] = 14000000
print(city)

13515271
35.6895
{'Name': 'Tokyo', 'Population': 14000000, 'Coordinates': (35.6895, 139.6917)}


## Exercise 8: List Operations

Given the list of cities from Exercise 3, perform the following operations:

1. Sort the list of cities alphabetically by name.
2. Create a new list that contains only the city names.
3. Remove the last city from the original list and print the updated list.

In [11]:
# Part 1
cities.sort()
print(cities)

# Part 2
city_names = [city[0] for city in cities]
print(city_names)

# Part 3
cities.pop()
print(cities)

[('Chicago', 41.8781, -87.6298), ('Los Angeles', 34.0522, -118.2437), ('Miami', 25.7617, -80.1918), ('New York City', 40.7128, -74.006)]
['Chicago', 'Los Angeles', 'Miami', 'New York City']
[('Chicago', 41.8781, -87.6298), ('Los Angeles', 34.0522, -118.2437), ('Miami', 25.7617, -80.1918)]


## Exercise 9: Dictionary Operations

Using the dictionary from Exercise 6, perform the following tasks:

1. Check if the key "Length" exists in the dictionary.
2. Print all the keys in the dictionary.
3. Print all the values in the dictionary.

In [12]:
# Part 1
print("length" in amzn)

# Part 2
print(amzn.keys())

# Part 3
print(amzn.values())

True
dict_keys(['name', 'length', 'countries', 'discharge'])
dict_values(['Amazon River', 6992, ['Brazil', 'Peru', 'Colombia'], 209000])


## Exercise 10: Practical Application

Imagine you have a list of tuples, each representing a location with its name, latitude, and longitude:

In [13]:
locations = [
    ("Mount Everest", 27.9881, 86.9250),
    ("K2", 35.8808, 76.5155),
    ("Kangchenjunga", 27.7025, 88.1475),
]

Perform the following tasks:

1. Create a new list that contains only the names of the locations.
2. Create a dictionary where the keys are location names and the values are tuples of their coordinates.
3. Print the latitude of "K2" using the dictionary.

In [14]:
# Part 1
names = [location[0] for location in locations]
print(names)

# Part 2
location_dict = {location[0]: (location[1], location[2]) for location in locations}
print(location_dict)

# Part 3
print(location_dict["K2"][0])

['Mount Everest', 'K2', 'Kangchenjunga']
{'Mount Everest': (27.9881, 86.925), 'K2': (35.8808, 76.5155), 'Kangchenjunga': (27.7025, 88.1475)}
35.8808


## Exercise 11: Manipulating Geographic Location Strings

- Create a string that represents the name of a geographic feature (e.g., `"Amazon River"`).
- Convert the string to lowercase and then to uppercase.
- Concatenate the string with the name of the country (e.g., `"Brazil"`) to create a full location name.
- Repeat the string three times, separating each repetition with a dash (`-`).

In [18]:
river = "Amazon River"

# Part 1
print(river.lower())
print(river.upper())

# Part 2
print(river + ", Brazil")

# Part 3
print(f'{river} - '* 3)

amazon river
AMAZON RIVER
Amazon River, Brazil
Amazon River - Amazon River - Amazon River - 


## Exercise 12: Extracting and Formatting Coordinates

- Given a string with the format `"latitude, longitude"` (e.g., `"40.7128N, 74.0060W"`), extract the numeric values of latitude and longitude.
- Convert these values to floats and remove the directional indicators (`N`, `S`, `E`, `W`).
- Format the coordinates into a `POINT` WKT string (e.g., `"POINT(-74.0060 40.7128)"`).

In [25]:
point = "40.7128N, 74.0060W"

# Extra numbers
lon = point[0:7]
lat = point[10:17]
print(f'{lat}, {lon}')

74.0060, 40.7128


## Exercise 13: Building Dynamic SQL Queries

- Given a table name and a condition, dynamically build an SQL query string.
- Example: If `table_name = "cities"` and `condition = "population > 1000000"`, the query should be `"SELECT * FROM cities WHERE population > 1000000;"`.
- Add additional conditions dynamically, like `AND` clauses.

In [26]:
table_name = "cities"
condition = "population > 1000000"

# Part 1
query = f"SELECT * FROM {table_name} WHERE {condition};"
print(query)


# Part 2 and 'AND'
condition2 = "area < 1000"
query = f"SELECT * FROM {table_name} WHERE {condition} AND {condition2};"
print(query)

SELECT * FROM cities WHERE population > 1000000;
SELECT * FROM cities WHERE population > 1000000 AND area < 1000;


## Exercise 14: String Normalization and Cleaning

- Given a list of city names with inconsistent formatting (e.g., `[" new york ", "Los ANGELES", "   CHICAGO"]`), normalize the names by:
  - Stripping any leading or trailing whitespace.
  - Converting them to title case (e.g., `"New York"`, `"Los Angeles"`, `"Chicago"`).
- Ensure that the output is a clean list of city names.

In [27]:
inconsistent = [" new york ", "Los ANGELES", "   CHICAGO"]

# Part 1
clean = [city.strip().title() for city in inconsistent]
print(clean)

['New York', 'Los Angeles', 'Chicago']


## Exercise 15: Parsing and Extracting Address Information

- Given a string in the format `"Street, City, Country"` (e.g., `"123 Main St, Springfield, USA"`), write a function that parses the string into a dictionary with keys `street`, `city`, and `country`.
- The function should return a dictionary like `{"street": "123 Main St", "city": "Springfield", "country": "USA"}`.

In [29]:
address = "123 Main St, Springfield, USA"

# Part 1
def parse_address(address):
    street, city, country = address.split(", ")
    return {"street": street, "city": city, "country": country}

print(parse_address(address))

{'street': '123 Main St', 'city': 'Springfield', 'country': 'USA'}


## Exercise 16: Using For Loops to Process Coordinate Lists

- Create a list of tuples representing coordinates (latitude, longitude).
- Write a `for` loop that prints each coordinate and indicates whether it is in the Northern or Southern Hemisphere based on the latitude.

In [30]:
coords = [
    (40.7128, -74.0060),
    (34.0522, -118.2437),
    (41.8781, -87.6298)
]

# Part 1
for coord in coords:
    if coord[0] > 0:
        print(f"{coord} is in the Northern Hemisphere")
    else:
        print(f"{coord} is in the Southern Hemisphere")

(40.7128, -74.006) is in the Northern Hemisphere
(34.0522, -118.2437) is in the Northern Hemisphere
(41.8781, -87.6298) is in the Northern Hemisphere


## Exercise 17: While Loops for Iterative Processing

- Create a list of coordinates (latitude, longitude).
- Write a `while` loop that continues to print each coordinate until it encounters a coordinate with a negative latitude.
- Stop the loop once this condition is met.

In [37]:
# Part 1
coords = ("40.7128", "74.0060"), ("34.0522", "-118.2437"),( "-41.8781", "87.6298")

# Part 2
i = 0
while float(coords[i][0]) > 0:
    print(coords[i])
    i += 1

('40.7128', '74.0060')
('34.0522', '-118.2437')


## Exercise 18: Conditional Logic in Loops

- Create a list of coordinates and use a `for` loop to iterate over them.
- Use an `if-elif-else` statement inside the loop to classify each coordinate based on its longitude:
  - Print `"Eastern Hemisphere"` if the longitude is greater than 0.
  - Print `"Western Hemisphere"` if the longitude is less than 0.

In [38]:
coords = [
    (40.7128, -74.0060),
    (34.0522, -118.2437),
    (41.8781, -87.6298)
]

# Part 1
for coord in coords:
    if coord[1] > 0:
        print("Eastern Hemisphere")
    elif coord[1] < 0:
        print("Western Hemisphere")

Western Hemisphere
Western Hemisphere
Western Hemisphere


## Exercise 19: Filtering Data with Combined Loops and Conditionals

- Given a list of coordinates, filter out and store only those located in the Southern Hemisphere (latitude < 0).
- Count the number of coordinates that meet this condition and print the result.

In [41]:
coords = [
    (40.7128, -74.0060),
    (-34.0522, -118.2437),
    (41.8781, -87.6298)
]

# Part 1
southern = []
for coord in coords:
    if coord[0] < 0:
        southern.append(coord)

# Part 2
print(len(southern))

1


## Exercise 20: Generating and Analyzing Random Coordinates

- Write a program that generates random coordinates (latitude between [-90, 90] degrees and longitude between [-180, 180] degrees).
- Use a `while` loop to keep generating coordinates until a pair with both latitude and longitude greater than 50 is generated.
- Print each generated coordinate and the final coordinate that meets the condition.

In [42]:
# Part 1
def random_coord():
    import random
    return (random.uniform(-90, 90), random.uniform(-180, 180))

# Part 2
while True:
    coord = random_coord()
    if coord[0] > 50 and coord[1] > 50:
        break

# Part 3
print(coord)

(87.39047814582912, 53.616811781621806)


## Submission Requirements

Complete the exercises above and and upload the notebook to your GitHub repository. Make sure the notebook has a Colab badge at the top so that it can be easily opened in Google Colab. Submit the URL of the notebook to Canvas.